{% set data = load_setup_py_data() %}

package:
  name: topmed_wgs_extraction
  version: {{ data['version'] }}

source:
  path: src
  
build:
  script: "python setup.py install"
  number: 1

about:
  home: https://changit.bwh.harvard.edu/rejpz/topmed_wgs_extraction
  license: GPL
  summary: Freeze.10 extraction and QC

test:
  commands:
    - topmed-wgs-extract --version
    - topmed-wgs-extract --help
    
requirements:
    build:
      - setuptools
    run:
      - snakemake==6.8.0
      
