package:
  name: topmed_wgs_extraction
  version: "1.0"

source:
  path: src
  
build:
  script: "python setup.py install"
  number: 1

about:
  home: https://changit.bwh.harvard.edu/rejpz/topmed_wgs_extraction
  license: GPL
  summary: Freeze.10 extraction and QC

test:
  commands:
    - topmed-wgs-extract
    
requirements:
    build:
      - setuptools
    run:
      - snakemake==6.8.0
