rule TEA:
    input:

rule generate_nwd_map:
    input:
    output: 'metadata/nwd_map.txt'
    shell:
        '/proj/relibs/relib00/python/2.7.3_x86_64_CentOS6.5/bin/python code/py27_generate_nwd_map.py > {output}'

rule generate_tor_map:
    input:
    output: "metadata/tor_mapping.txt"
    shell:
        '/proj/relibs/relib00/python/2.7.3_x86_64_CentOS6.5/bin/python code/py27_generate_tor_map.py > {output}'
