studies: [GECOPD]
external_reference_base: "/proj/regeps/regep00/studies/COPDGene/data/genotype/data/freezes/king_ref_GRCh38/king_ref_GRCh38"
output_base: "methylation_ref_concordance/gecopd_freeze.10_concordance_report"
batch_count: 12
GECOPD:
  known_good_reference: "/proj/regeps/regep00/studies/COPDGene/data/genotype/data/freezes/king_ref_GRCh38/king_ref_GRCh38"
datasets:
  - id: 0
    name: "wgs"
    manifest_path: "/proj/regeps/regep00/studies/TopMed/data/dna/whole_genome/TopMed/data/freezes/freeze.10a/manifests/nwdids.txt"
    sample_type_code: "d"
    gender_observations: "tmp/GECOPD.sexcheck"
    gender_observations_sample_column: "IID"
    gender_observations_column: "SNPSEX"
    gender_observations_delim_whitespace: True
  - id: 1
    name: "ref"
    manifest_path: "/proj/regeps/regep00/studies/COPDGene/data/genotype/data/freezes/king_ref_GRCh38/king_ref_GRCh38.fam"
    sample_type_code: "d"
    #gender_observations: "/proj/regeps/regep00/studies/COPDGene/data/genotype/data/freezes/king_ref_GRCh38/king_ref_GRCh38.fam"
    #gender_observations_sample_column: 1
    #gender_observations_column: 5
    #gender_observations_delim_whitespace: True
concordance_observations:
  - cobs_0: 0
    path: "tmp/GECOPD_king.kin0"
    type: "raw"
    cutoff: 0.354
    query_dataset: 0
    reference_dataset: 1
    concord_column_label: 'Kinship'
