pepfile: "/proj/regeps/regep00/studies/GECOPD/data/dna/whole_genome/TopMed/data/canonical/GECOPD_freeze.10.pep.yaml"
extract_dir: "/d/tmp/regeps/regep00/studies/COPDGene/data/dna/whole_genome/TopMed/data/freezes/20220131/"
